/**
 * database.types.ts
 *
 * In a real project, the top-level Database interface is generated by the
 * Supabase CLI:  npx supabase gen types typescript --project-id <id> > src/shared/types/database.types.ts
 *
 * You commit this file and regenerate it whenever the schema changes.
 * This makes every Supabase query fully typed — column names, return shapes,
 * filter values. A typo in a column name is a compile error, not a runtime bug.
 *
 * The hand-written domain types below (Profile, AnalyticsEvent, etc.)
 * derive from the generated types via the helper utilities at the bottom.
 * This means they stay in sync with the DB automatically.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

// ─── Generated by Supabase CLI ────────────────────────────────────────────────
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          email: string
          full_name: string | null
          avatar_url: string | null
          role: 'owner' | 'admin' | 'member' | 'viewer'
          organization_id: string
          onboarding_completed: boolean
          preferences: Json
        }
        Insert: {
          id: string
          created_at?: string
          updated_at?: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'owner' | 'admin' | 'member' | 'viewer'
          organization_id: string
          onboarding_completed?: boolean
          preferences?: Json
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'owner' | 'admin' | 'member' | 'viewer'
          organization_id?: string
          onboarding_completed?: boolean
          preferences?: Json
        }
      }
      organizations: {
        Row: {
          id: string
          created_at: string
          name: string
          slug: string
          plan: 'free' | 'pro' | 'enterprise'
          settings: Json
        }
        Insert: {
          id?: string
          created_at?: string
          name: string
          slug: string
          plan?: 'free' | 'pro' | 'enterprise'
          settings?: Json
        }
        Update: {
          id?: string
          created_at?: string
          name?: string
          slug?: string
          plan?: 'free' | 'pro' | 'enterprise'
          settings?: Json
        }
      }
      analytics_events: {
        Row: {
          id: string
          created_at: string
          organization_id: string
          event_type: string
          user_id: string | null
          session_id: string | null
          properties: Json
          page_url: string | null
          referrer: string | null
          country: string | null
          device_type: 'desktop' | 'mobile' | 'tablet' | null
        }
        Insert: {
          id?: string
          created_at?: string
          organization_id: string
          event_type: string
          user_id?: string | null
          session_id?: string | null
          properties?: Json
          page_url?: string | null
          referrer?: string | null
          country?: string | null
          device_type?: 'desktop' | 'mobile' | 'tablet' | null
        }
        Update: Partial<Database['public']['Tables']['analytics_events']['Insert']>
      }
      audit_logs: {
        Row: {
          id: string
          created_at: string
          organization_id: string
          actor_id: string
          actor_email: string
          action: string
          resource_type: string
          resource_id: string | null
          metadata: Json
          ip_address: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          organization_id: string
          actor_id: string
          actor_email: string
          action: string
          resource_type: string
          resource_id?: string | null
          metadata?: Json
          ip_address?: string | null
        }
        Update: Partial<Database['public']['Tables']['audit_logs']['Insert']>
      }
      notifications: {
        Row: {
          id: string
          created_at: string
          organization_id: string
          user_id: string
          type: 'info' | 'warning' | 'error' | 'success'
          title: string
          body: string
          read: boolean
          action_url: string | null
          metadata: Json
        }
        Insert: {
          id?: string
          created_at?: string
          organization_id: string
          user_id: string
          type: 'info' | 'warning' | 'error' | 'success'
          title: string
          body: string
          read?: boolean
          action_url?: string | null
          metadata?: Json
        }
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>
      }
      ai_insights: {
        Row: {
          id: string
          created_at: string
          organization_id: string
          type: 'anomaly' | 'trend' | 'recommendation' | 'summary'
          title: string
          content: string
          severity: 'low' | 'medium' | 'high' | null
          metric_key: string | null
          data_snapshot: Json
          acknowledged: boolean
        }
        Insert: {
          id?: string
          created_at?: string
          organization_id: string
          type: 'anomaly' | 'trend' | 'recommendation' | 'summary'
          title: string
          content: string
          severity?: 'low' | 'medium' | 'high' | null
          metric_key?: string | null
          data_snapshot?: Json
          acknowledged?: boolean
        }
        Update: Partial<Database['public']['Tables']['ai_insights']['Insert']>
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_analytics_summary: {
        Args: {
          org_id: string
          start_date: string
          end_date: string
        }
        Returns: {
          total_events: number
          unique_sessions: number
          unique_users: number
          top_pages: Json
          device_breakdown: Json
          country_breakdown: Json
        }
      }
    }
    Enums: {
      user_role: 'owner' | 'admin' | 'member' | 'viewer'
      org_plan: 'free' | 'pro' | 'enterprise'
    }
  }
}

// ─── Convenience type helpers ─────────────────────────────────────────────────
// These derive domain types from the generated schema so they never drift.

type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

// Domain types — use these throughout the app, never the raw Row types directly
export type Profile = Tables<'profiles'>
export type Organization = Tables<'organizations'>
export type AnalyticsEvent = Tables<'analytics_events'>
export type AuditLog = Tables<'audit_logs'>
export type Notification = Tables<'notifications'>
export type AiInsight = Tables<'ai_insights'>

// Role hierarchy — useful for permission checks
export type UserRole = Database['public']['Enums']['user_role']
export type OrgPlan = Database['public']['Enums']['org_plan']

export const ROLE_HIERARCHY: Record<UserRole, number> = {
  owner: 4,
  admin: 3,
  member: 2,
  viewer: 1,
}

/**
 * Returns true if the given role has at least the required permission level.
 *
 * Usage:
 *   hasPermission(user.role, 'admin')  // true for owner, admin
 *   hasPermission(user.role, 'member') // true for owner, admin, member
 */
export function hasPermission(userRole: UserRole, requiredRole: UserRole): boolean {
  return ROLE_HIERARCHY[userRole] >= ROLE_HIERARCHY[requiredRole]
}